### ISSUE TITLE
Fix Memory Leak

### ISSUE THREAD

**Issue by braxtonhall** [braxtonhall/codeshovel-webservice#1]
Error frequently thrown:
```
2019-07-18 23:34:48.975 ERROR 1 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181) ~[na:1.8.0_212]
	at java.util.ArrayList.grow(ArrayList.java:265) ~[na:1.8.0_212]
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239) ~[na:1.8.0_212]
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231) ~[na:1.8.0_212]
	at java.util.ArrayList.add(ArrayList.java:462) ~[na:1.8.0_212]
	at com.github.javaparser.GeneratedJavaParserTokenManager.CommonTokenAction(GeneratedJavaParserTokenManager.java:93) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:2745) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_scan_token(GeneratedJavaParser.java:10140) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_3R_58(GeneratedJavaParser.java:6510) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_3_3(GeneratedJavaParser.java:6524) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_3R_108(GeneratedJavaParser.java:6572) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_3R_130(GeneratedJavaParser.java:6885) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_3R_84(GeneratedJavaParser.java:6912) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_3_16(GeneratedJavaParser.java:7563) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.jj_2_16(GeneratedJavaParser.java:5776) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1639) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.SwitchEntry(GeneratedJavaParser.java:4170) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.SwitchStatement(GeneratedJavaParser.java:4142) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3726) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3897) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1644) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3817) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1251) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:952) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:846) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:408) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:913) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:846) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:408) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:154) ~[codeshovel-52542b1059.jar!/:na]
	at com.github.javaparser.ParseStart$$Lambda$440/1331072334.parse(Unknown Source) ~[na:na]
	at com.github.javaparser.JavaParser.parse(JavaParser.java:126) ~[codeshovel-52542b1059.jar!/:na]
```

**Comment by braxtonhall** [comment]
This is a problem with codeshovel, not codeshovel-webservice
